version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_new
    ports:
      - "8082:8080"
      - "50000:50000"
      
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9095:9090"
      
  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"
    volumes:
      - grafana-storage:/var/lib/grafana  # Ensure this line is added

volumes:  # Add this section
  grafana-storage:  # Declare the named volume
