name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (modify as needed)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests scikit-learn openai pdfkit matplotlib

      # Step 4: Collect GitHub Data
      - name: Collect Commit and PR Data
        run: |
          python collect_vcs_data.py

      # Step 5: Run tests (optional)
      - name: Run Tests
        run: |
          echo "Run your test scripts here"

      # Step 6: Analyze Data (ML & LLM)
      - name: Analyze Data
        run: |
          python analyze_vcs_data.py

      # Step 7: Generate DevOps Report
      - name: Generate Report
        run: |
          python generate_report.py

      # Step 8: Upload Report as Artifact (Optional)
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: devops-report
          path: devops_maturity_report.pdf
